blank_issues_enabled: false
contact_links:
  - name: GitHub Community Support
    url: https://github.com/yourusername/stagelog/discussions
    about: Please ask and answer questions here.
  - name: Documentation
    url: https://github.com/yourusername/stagelog/tree/main/docs
    about: Check our documentation for detailed guides.
